---
- name: Create a simple vm
  hosts: localhost
  gather_facts: False
  collections:
    - ovirt.ovirt
  vars_files:
    - credentials.yaml
  vars:
    engine_fqdn: "{{ engine_fqdn }}"
    engine_user: "{{ ovirt_username }}"
    engine_password: "{{ ovirt_pwd }}"
    cluster_name: "{{ cluster_name }}"
    stop_non_migratable_vms: true
    host_statuses:
      - up
  roles:
    - cluster_upgrade
